[build]
  publish = "public"
  command = "npm install"
  environment = { NODE_VERSION = "20" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  [functions.timeout]
    default = 26
  external_node_modules = [
    "better-sqlite3",
    "nodemailer",
    "@netlify/functions",
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
